project:
  name: "RGBD-Tracker"
  debug_mode: true

input:
  source: "realsense" # Options: "realsense", "video_file"

realsense:
  width: 640
  height: 480
  fps: 30

video_file:
  path: "data/video_samples/walking.mp4"
  loop: true

models:
  grounding_dino: 
    weights: "./weights/groundingdino_swint_ogc.pth"
    config: "./config/GroundingDINO_SwinT_OGC.py"
  recognize_anything: 
    weights: "./weights/ram_plus_swin_large_14m.pth"
    config: ""
  sam_checkpoint: 
    weights: "./weights/sam2_hiera_large.pt"
    config: "sam2_hiera_l.yaml"
  device: "cuda" # or "cpu"